# Generated by Django 5.2.7 on 2025-11-11 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooventory', '0002_rename_animal_myanimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=100, null=True)),
                ('phylum', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_class', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('genus', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unique Animal',
                'verbose_name_plural': 'Unique Animals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('feeding', 'Feeding'), ('weight_update', 'Weight Update'), ('note', 'Note'), ('other', 'Other')], default='feeding', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_fed', models.FloatField(blank=True, null=True)),
                ('measurement', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='zooventory.food')),
                ('myanimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='zooventory.myanimal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myanimal',
            name='unique_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='zooventory.uniqueanimal'),
        ),
    ]
