# Generated by Django 5.2.7 on 2025-11-18 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooventory', '0003_uniqueanimal_log_myanimal_unique_animal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueanimal',
            name='characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueanimal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
